### ISSUE TITLE
TypeError: Cannot read properties of undefined (reading 'prototype')

### ISSUE THREAD

**Issue by danass** [Mastermindzh/react-cookie-consent#194]
Using Nextjs framework, the import statement actually just crash it.

import CookieConsent from "react-cookie-consent";

 ⨯ node_modules/react-cookie-consent/dist/react-cookie-consent.cjs.development.js (43:48) @ prototype
 ⨯ TypeError: Cannot read properties of undefined (reading 'prototype')
    at __webpack_require__ (/home/fauxprophet/Documents/Ops/Novaregia/Web/nv-flore/.next/server/webpack-runtime.js:33:43)
    at __webpack_require__ (/home/fauxprophet/Documents/Ops/Novaregia/Web/nv-flore/.next/server/webpack-runtime.js:33:43)
    at eval (./app/layout.js:10:78)
    at (rsc)/./app/layout.js (/home/fauxprophet/Documents/Ops/Novaregia/Web/nv-flore/.next/server/app/page.js:204:1)
    at Function.__webpack_require__ (/home/fauxprophet/Documents/Ops/Novaregia/Web/nv-flore/.next/server/webpack-runtime.js:33:43)
digest: "2698489716"

 ⨯ node_modules/react-cookie-consent/dist/react-cookie-consent.cjs.development.js (43:48) @ prototype
 ⨯ TypeError: Cannot read properties of undefined (reading 'prototype')
    at _inheritsLoose (webpack-internal:///(rsc)/./node_modules/react-cookie-consent/dist/react-cookie-consent.cjs.development.js:36:51)
    at eval (webpack-internal:///(rsc)/./node_modules/react-cookie-consent/dist/react-cookie-consent.cjs.development.js:212:5)
    at eval (webpack-internal:///(rsc)/./node_modules/react-cookie-consent/dist/react-cookie-consent.cjs.development.js:420:2)
    at (rsc)/./node_modules/react-cookie-consent/dist/react-cookie-consent.cjs.development.js (/home/fauxprophet/Documents/Ops/Novaregia/Web/nv-flore/.next/server/vendor-chunks/react-cookie-consent.js:30:1)
    at __webpack_require__ (/home/fauxprophet/Documents/Ops/Novaregia/Web/nv-flore/.next/server/webpack-runtime.js:33:43)
    at eval (webpack-internal:///(rsc)/./node_modules/react-cookie-consent/dist/index.js:3:22)
    at (rsc)/./node_modules/react-cookie-consent/dist/index.js (/home/fauxprophet/Documents/Ops/Novaregia/Web/nv-flore/.next/server/vendor-chunks/react-cookie-consent.js:20:1)
    at __webpack_require__ (/home/fauxprophet/Documents/Ops/Novaregia/Web/nv-flore/.next/server/webpack-runtime.js:33:43)
    at eval (webpack-internal:///(rsc)/./app/layout.js:10:78)
    at (rsc)/./app/layout.js (/home/fauxprophet/Documents/Ops/Novaregia/Web/nv-flore/.next/server/app/rain/page.js:193:1)
    at Function.__webpack_require__ (/home/fauxprophet/Documents/Ops/Novaregia/Web/nv-flore/.next/server/webpack-runtime.js:33:43)
    at runNextTicks (node:internal/process/task_queues:60:5)
    at listOnTimeout (node:internal/timers:540:9)
    at process.processTimers (node:internal/timers:514:7)
    at async e_ (/home/fauxprophet/Documents/Ops/Novaregia/Web/nv-flore/node_modules/next/dist/compiled/next-server/app-page.runtime.dev.js:11:405095)
    at async eJ (/home/fauxprophet/Documents/Ops/Novaregia/Web/nv-flore/node_modules/next/dist/compiled/next-server/app-page.runtime.dev.js:11:409224)
    at async eG (/home/fauxprophet/Documents/Ops/Novaregia/Web/nv-flore/node_modules/next/dist/compiled/next-server/app-page.runtime.dev.js:11:409699)
    at async eX (/home/fauxprophet/Documents/Ops/Novaregia/Web/nv-flore/node_modules/next/dist/compiled/next-server/app-page.runtime.dev.js:11:413242)
    at async /home/fauxprophet/Documents/Ops/Novaregia/Web/nv-flore/node_modules/next/dist/compiled/next-server/app-page.runtime.dev.js:11:413716 {
  digest: '844882894',
  page: '/'
}

System Ubuntu 22

**Comment by joel-gfdez** [comment]
Exact same problem here, just placed it in my main layout like this:
```jsx
    <CookieConsent
      location="bottom"
      onAccept={(scrolled) => {
        if (scrolled) {
          console.log('[cookie-consent] scrolled');
        } else {
          console.log('[cookie-consent] accepted');
        }
      }}
    />
```

Using NextJS version 13.4.19.

**Comment by iSyqozz** [comment]
same problem here aswell

**Comment by Mastermindzh** [comment]
Hey,

Probably has to do with cookies (nor the interface) not being available on the server side.

I can probably have a look at it this weekend.

**Comment by jotapemattos** [comment]
I separated the cookies into a client-side component and rendered it in the layout. it worked for me

**Comment by Mastermindzh** [comment]
Thanks @jotapemattos, that confirms my suspicion about the others using it as a server-side component (which isn't supported).


@danass @joel-gfdez , to use a client-side component in next.js simply add: `use client` to the top of a component file like so:

```jsx
'use client'
 
import { useState } from 'react'
 
export default function Counter() {
  const [count, setCount] = useState(0)
 
  return (
    <div>
      <p>You clicked {count} times</p>
      <button onClick={() => setCount(count + 1)}>Click me</button>
    </div>
  )
}

```

**Comment by joel-gfdez** [comment]
@Mastermindzh @jotapemattos Thanks for the tip, wrapping it in a client component worked flawlessly.

**Comment by AmitMali** [comment]
its because of server component, simply create  your client component make ,  setup code there . use your component it will work
